export const baseCollections = {
  typographic: {
    colors: { bg: '#F6DEB6', fg: '#C07E16', mutedBg: '#FCF3E5', mutedFg: '#ECB35A' },
    stamps: [
      {
        year: '1959-03-06',
        country: 'Uruguay',
        src: '/stamps/typographic/uruguay1.svg',
        srcLg: '/stamps/typographic/lg/uruguay1.webp',
        srcOriginal: '/stamps/reference/uruguay.webp',
        catalogCodes: [
          'Michel UY 842',
          'Stamp Number UY C196',
          'Yvert et Tellier UY PA181',
          'Stanley Gibbons UY 1104',
        ],
        meta: {
          category: 'Anniversaries and Jubilees',
          designer: 'unknown',
          faceValue: '38 Uruguayan centésimos',
          printRun: '500,000',
        },
      },
      {
        year: '1959-03-06',
        country: 'Uruguay',
        src: '/stamps/typographic/uruguay2.svg',
        srcLg: '/stamps/typographic/lg/uruguay2.webp',
        srcOriginal: '/stamps/reference/uruguay.webp',
        catalogCodes: [
          'Michel UY 842',
          'Stamp Number UY C196',
          'Yvert et Tellier UY PA181',
          'Stanley Gibbons UY 1104',
        ],
        meta: {
          category: 'Anniversaries and Jubilees',
          designer: 'unknown',
          faceValue: '38 Uruguayan centésimos',
          printRun: '500,000',
        },
      },
      {
        year: '1959-03-06',
        country: 'Uruguay',
        src: '/stamps/typographic/uruguay3.svg',
        srcLg: '/stamps/typographic/lg/uruguay3.webp',
        srcOriginal: '/stamps/reference/uruguay.webp',
        catalogCodes: [
          'Michel UY 842',
          'Stamp Number UY C196',
          'Yvert et Tellier UY PA181',
          'Stanley Gibbons UY 1104',
        ],
        meta: {
          category: 'Anniversaries and Jubilees',
          designer: 'unknown',
          faceValue: '38 Uruguayan centésimos',
          printRun: '500,000',
        },
      },
      {
        year: '1959-03-06',
        country: 'Uruguay',
        src: '/stamps/typographic/uruguay4.svg',
        srcLg: '/stamps/typographic/lg/uruguay4.webp',
        srcOriginal: '/stamps/reference/uruguay.webp',
        catalogCodes: [
          'Michel UY 842',
          'Stamp Number UY C196',
          'Yvert et Tellier UY PA181',
          'Stanley Gibbons UY 1104',
        ],
        meta: {
          category: 'Anniversaries and Jubilees',
          designer: 'unknown',
          faceValue: '38 Uruguayan centésimos',
          printRun: '500,000',
        },
      },
      {
        year: '1959-03-06',
        country: 'Gibraltar',
        src: '/stamps/typographic/gibraltar1.svg',
        srcLg: '/stamps/typographic/lg/gibraltar1.webp',
        srcOriginal: '/stamps/reference/gibraltar.webp',
        catalogCodes: [
          'Michel GI 565',
          'Stamp Number GI 545',
          'Yvert et Tellier GI 575',
          'Stanley Gibbons GI 609',
        ],
        meta: {
          category: 'Anniversaries and Jubilees',
          designer: 'unknown',
          faceValue: '4 Gibraltar pence',
          printRun: '500,000',
        },
      },
      {
        year: '1959-03-06',
        country: 'Gibraltar',
        src: '/stamps/typographic/gibraltar2.svg',
        srcLg: '/stamps/typographic/lg/gibraltar2.webp',
        srcOriginal: '/stamps/reference/gibraltar.webp',

        catalogCodes: [
          'Michel GI 565',
          'Stamp Number GI 545',
          'Yvert et Tellier GI 575',
          'Stanley Gibbons GI 609',
        ],
        meta: {
          category: 'Anniversaries and Jubilees',
          designer: 'unknown',
          faceValue: '4 Gibraltar pence',
          printRun: '500,000',
        },
      },
      {
        year: '1959-03-06',
        country: 'Gibraltar',
        src: '/stamps/typographic/gibraltar3.svg',
        srcLg: '/stamps/typographic/lg/gibraltar3.webp',
        srcOriginal: '/stamps/reference/gibraltar.webp',

        catalogCodes: [
          'Michel GI 565',
          'Stamp Number GI 545',
          'Yvert et Tellier GI 575',
          'Stanley Gibbons GI 609',
        ],
        meta: {
          category: 'Anniversaries and Jubilees',
          designer: 'unknown',
          faceValue: '4 Gibraltar pence',
          printRun: '500,000',
        },
      },
      {
        year: '1959-03-06',
        country: 'Gibraltar',
        src: '/stamps/typographic/gibraltar4.svg',
        srcLg: '/stamps/typographic/lg/gibraltar4.webp',
        srcOriginal: '/stamps/reference/gibraltar.webp',

        catalogCodes: [
          'Michel GI 565',
          'Stamp Number GI 545',
          'Yvert et Tellier GI 575',
          'Stanley Gibbons GI 609',
        ],
        meta: {
          category: 'Anniversaries and Jubilees',
          designer: 'unknown',
          faceValue: '4 Gibraltar pence',
          printRun: '500,000',
        },
      },
    ],
  },
  textured: {
    stamps: [
      {
        year: '1974',
        country: 'Algeria',
        src: '/stamps/textured/algerie.webp',
        srcLg: '/stamps/textured/lg/algerie.webp',
        srcOriginal: '/stamps/reference/algerie.webp',

        catalogCodes: [
          'Michel GI 638',
          'Stamp Number GI 528',
          'Yvert et Tellier GI 595',
          'Stanley Gibbons GI 653',
        ],
        meta: {
          category: '17th-century brassware',
          designer: 'unknown',
          faceValue: '0.60 Algerian dinars',
          printRun: 'unknown',
        },
      },
      {
        year: '1973-11-09',
        country: 'Germany',
        src: '/stamps/textured/germany.webp',
        srcLg: '/stamps/textured/lg/germany.webp',
        srcOriginal: '/stamps/reference/germany.webp',

        catalogCodes: [
          'Michel DE 790',
          'Stamp Number DE B507',
          'Yvert et Tellier DE 639',
          'Stanley Gibbons DE 1678',
        ],
        meta: {
          category: 'Charity / Christmas semi-postal',
          designer: 'Isolde Monson-Baumgart',
          faceValue: '30+15 pfennigs',
          printRun: '8,797,000',
        },
      },
      {
        year: '1991-08-26',
        country: 'Falkland Islands',
        width: 130,
        height: 190,
        src: '/stamps/textured/falkland-islands.webp',
        srcLg: '/stamps/textured/lg/falkland-islands.webp',
        srcOriginal: '/stamps/reference/falkland-islands.webp',
        catalogCodes: [
          'Michel FK 541',
          'Stamp Number FK 538',
          'Yvert et Tellier FK 556',
          'Stanley Gibbons FK 636',
        ],
        meta: {
          category: 'Animals (Fauna) ',
          designer: 'Ian John Strange',
          faceValue: '20 Falkland Islands pence',
          printRun: '155,000',
        },
      },
      {
        year: '1960-02-06',
        country: 'Argentina',
        src: '/stamps/textured/argentina.webp',
        srcLg: '/stamps/textured/lg/argentina.webp',
        srcOriginal: '/stamps/reference/argentina.webp',
        catalogCodes: [
          'Michel AR 716',
          'Stamp Number AR B23',
          'Yvert et Tellier AR 614',
          'Stanley Gibbons AR 965',
        ],
        meta: {
          category: 'Animals (Fauna)',
          designer: 'Horacio Romulo Alvarez Boero',
          faceValue: '50+20 Argentine centavos',
          printRun: '500,000',
        },
      },

      {
        year: '1937-05-01',
        country: 'Great Britain',
        src: '/stamps/textured/great-britain.webp',
        srcLg: '/stamps/textured/lg/great-britain.webp',
        srcOriginal: '/stamps/reference/great-britain.webp',
        catalogCodes: [
          'Michel GB —',
          'Stamp Number GB —',
          'Yvert et Tellier GB —',
          'Stanley Gibbons GB D28',
        ],
        meta: {
          category: 'Postage Due',
          designer: 'George W. Eve',
          faceValue: 'one penny',
          printRun: 'unknown',
        },
      },
      {
        year: '1930-10-20',
        country: 'Italy',
        src: '/stamps/textured/italy.webp',
        srcLg: '/stamps/textured/lg/italy.webp',
        srcOriginal: '/stamps/reference/italy.webp',
        catalogCodes: [
          'Michel IT 340',
          'Stamp Number IT 276/80',
          'Yvert et Tellier IT —',
          'Stanley Gibbons IT —',
        ],
        meta: {
          category: 'Anniversaries and Jubilees',
          designer: 'Dino Tofani',
          faceValue: '5+2 Italian lire',
          printRun: '12,000',
        },
      },
      {
        year: '1987-01-02',
        country: 'Mozambique',
        width: 225,
        height: 150,
        src: '/stamps/textured/mocambique.webp',
        srcLg: '/stamps/textured/lg/mocambique.webp',
        srcOriginal: '/stamps/reference/mocambique.webp',
        catalogCodes: [
          'Michel MZ 1397',
          'Stamp Number MZ 1304',
          'Yvert et Tellier MZ 1401AW',
          'Stanley Gibbons MZ 1464a',
        ],
        meta: {
          category: 'Minerals / Gemstones',
          designer: 'unknown',
          faceValue: '8 Mozambican meticais',
          printRun: 'unknown',
        },
      },
    ],
    colors: { bg: '#E5D2DD', fg: '#A45684', mutedBg: '#F8F3F6', mutedFg: '#CC9EB9' },
  },
  monoline: {
    stamps: [
      {
        year: '1989-08-04',
        country: 'Canada',
        src: '/stamps/monoline/canada.svg',
        srcLg: '/stamps/monoline/lg/canada.webp',
        srcOriginal: '/stamps/reference/canada.webp',
        catalogCodes: [
          'Michel CA 1142',
          'Stamp Number CA 1247',
          'Yvert et Tellier CA 1106',
          'Stanley Gibbons CA 1333',
        ],
        meta: {
          category: 'Mushrooms & Fungi',
          designer: 'Ernst Roch',
          faceValue: '38 Canadian cents',
          printRun: '3,610,200',
        },
      },
        {
        year: '1989-08-04',
        country: 'Great Britain',
        src: '/stamps/monoline/great-britain.svg',
        srcLg: '/stamps/monoline/lg/great-britain.webp',
        srcOriginal: '/stamps/reference/great-britain.webp',
        width: 185,
      catalogCodes: [
          'Michel GB —',
          'Stamp Number GB —',
          'Yvert et Tellier GB —',
          'Stanley Gibbons GB D28',
        ],
        meta: {
          category: 'Postage Due',
          designer: 'George W. Eve',
          faceValue: 'one penny',
          printRun: 'unknown',
        },
      },
      {
        year: '1964-12-14',
        country: 'Ghana',
        src: '/stamps/monoline/ghana.svg',
        srcLg: '/stamps/monoline/lg/ghana.webp',
        srcOriginal: '/stamps/reference/ghana.webp',
        width: 185,
        catalogCodes: [
          'Michel GH 198A',
          'Stamp Number GH 192',
          'Yvert et Tellier GH 181',
          'Stanley Gibbons GH 357',
        ],
        meta: {
          category: 'Animals (Fauna)',
          designer: 'Anthony S. B. New',
          faceValue: '1 Ghanaian penny',
          printRun: 'unknown',
        },
      },
      {
        year: '1984-02-09',
        country: 'Sweden ',
        src: '/stamps/monoline/sweden.svg',
        srcLg: '/stamps/monoline/lg/sweden.webp',
        srcOriginal: '/stamps/reference/sweden.webp',
        width: 225,
        catalogCodes: [
          'Michel SE 1271',
          'Stamp Number SE 1487',
          'Yvert et Tellier SE 1253',
          'Stanley Gibbons SE 1184',
        ],
        meta: {
          category: 'Europa (C.E.P.T.)',
          designers: ['Jacky Larrivière', 'Lars Sjööblom'],
          faceValue: '2.70 Swedish krona',
          printRun: '8,954,000',
        },
      },
      {
        year: '1920-09-01',
        country: 'Czechoslovakia ',
        src: '/stamps/monoline/czechoslovakia.svg',
        srcLg: '/stamps/monoline/lg/czechoslovakia.webp',
        srcOriginal: '/stamps/reference/czechoslovakia.webp',
        width: 170,
        catalogCodes: [
          'Michel CS 168A',
          'Stamp Number CS 85a',
          'Yvert et Tellier CS 163',
          'Stanley Gibbons CS 194a',
        ],
        meta: {
          category: 'Animals (Fauna)',
          designers: 'Jaroslav Benda',
          faceValue: '25 Czechoslovak haléř',
          printRun: '37,330,000',
        },
      },
      {
        year: '1968-06-27',
        country: 'United States of America',
        src: '/stamps/monoline/USA-voting.svg',
        srcLg: '/stamps/monoline/lg/USA-voting.webp',
        srcOriginal: '/stamps/reference/USA-voting.webp',
        width: 150,
        catalogCodes: [
          'Michel US 950',
          'Stamp Number US 1344',
          'Yvert et Tellier US 847',
          'Stanley Gibbons US 1329',
        ],
        meta: {
          category: 'Animals (Fauna) | Elections',
          designers: ['B. Hyde', 'N. Todhunter', 'Arthur W. Dintaman'],          
          faceValue: '6 United States cent',
          printRun: '159,000,000',
        },
      },
    
      {
        year: '1964-05-19',
        country: 'Monaco',
        src: '/stamps/monoline/monaco.svg',
        srcLg: '/stamps/monoline/lg/monaco.webp',
        srcOriginal: '/stamps/reference/monaco.webp',
        width: 180,
        height: 176,
        catalogCodes: [
          'Michel MC 775',
          'Stamp Number MC 583',
          'Yvert et Tellier MC 539B',
          'Stanley Gibbons MC 673',
        ],
        meta: {
          category: 'Sea life',
          designer: ['Pierre Béquet', 'Pierrette Lambert'],
          faceValue: '0.12 Monegasque francs',
          printRun: '2,697,320',
        },
      },

      {
        year: '1967-12-11',
        country: 'United States of America',
        src: '/stamps/monoline/USA-mississippi.svg',
        srcLg: '/stamps/monoline/lg/USA-mississippi.webp',
        srcOriginal: '/stamps/reference/USA-mississippi.webp',
        width: 200,
        height: 134,
        catalogCodes: [
          'Michel US 938',
          'Stamp Number US 1337',
          'Yvert et Tellier US 841',
          'Stanley Gibbons US 1317',
        ],
        meta: {
          category: 'Anniversaries and Jubilees',
          designer: ['Andrew Bucci', 'J. Creamer'],
          faceValue: '5 United States cents',
          printRun: '113,000,000',
        },
      },
      {
        year: '1967-09-29',
        country: 'Australia',
        src: '/stamps/monoline/australia.svg',
        srcLg: '/stamps/monoline/lg/australia.webp',
        srcOriginal: '/stamps/reference/australia.webp',
        width: 170,
        height: 134,
        catalogCodes: [
          'Michel AU 391A',
          'Stamp Number AU 399',
          'Yvert et Tellier AU 323A',
          'Stanley Gibbons AU 386c',
        ],
        meta: {
          category: 'Crowns and Coronets',
          designer: 'P. E. Morriss',
          faceValue: '5 Australian cents',
          printRun: '1,672,194,000',
        },
      },
      {
        year: '1971-03-25',
        country: 'Czechoslovakia',
        src: '/stamps/monoline/ceskoslovensko.svg',
        srcLg: '/stamps/monoline/lg/ceskoslovensko.webp',
        srcOriginal: '/stamps/reference/ceskoslovensko.webp',
        width: 200,
        height: 170,
        catalogCodes: [
          'Michel CS 1991x',
          'Stamp Number CS 1740',
          'Yvert et Tellier CS 1838',
          'Stanley Gibbons CS 1945',
        ],
        meta: {
          category: 'Buildings',
          designer: ['Jaroslav Lukavský', 'Miloš Ondráček'],
          faceValue: '9 Czechoslovak korunas',
          printRun: '34,645,000',
        },
      },
      {
        year: '1977-10-21',
        country: 'United States of America',
        src: '/stamps/monoline/USA-christmas.svg',
        srcLg: '/stamps/monoline/lg/USA-christmas.webp',
        srcOriginal: '/stamps/reference/USA-christmas.webp',
        width: 190,
        catalogCodes: [
          'Michel US 1318',
          'Stamp Number US 1730',
          'Yvert et Tellier US 1176',
          'Stanley Gibbons US 1706',
        ],
        meta: {
          category: 'Christmas',
          designer: 'Dolli Tingle Brackett',
          faceValue: '13 United States cents',
          printRun: '922,000,000',
        },
      },
      {
        year: '1969-03-12',
        country: 'Nicaragua',
        src: '/stamps/monoline/nicaragua.svg',
        srcLg: '/stamps/monoline/lg/nicaragua.webp',
        srcOriginal: '/stamps/reference/nicaragua.webp',
        width: 140,
        catalogCodes: [
          'Michel NI 2835',
          'Stamp Number NI C667-76',
          'Yvert et Tellier NI —',
          'Stanley Gibbons NI —',
        ],
        meta: {
          category: 'Animals (Fauna)',
          designer: 'unknown',
          faceValue: '1 Nicaraguan Córdoba',
          printRun: 'unknown',
        },
      },
      {
        year: '1977-07-28',
        country: 'Yugoslavia',
        src: '/stamps/monoline/jugoslavija.svg',
        srcLg: '/stamps/monoline/lg/jugoslavija.webp',
        srcOriginal: '/stamps/reference/jugoslavija.webp',
        width: 130,
        height: 168,
        catalogCodes: [
          'Michel YU 1695',
          'Stamp Number YU 1153',
          'Yvert et Tellier YU 1620',
          'Stanley Gibbons YU 1566a',
        ],
        meta: {
          category: 'Post Horns',
          designer: 'unknown',
          faceValue: '1 Yugoslav dinar',
          printRun: 'unknown',
        },
      },
      {
        year: '2012-02-11',
        country: 'Latvia',
        src: '/stamps/monoline/latvia.svg',
        srcLg: '/stamps/monoline/lg/latvia.webp',
        srcOriginal: '/stamps/reference/latvia.webp',
        width: 160,
        catalogCodes: [
          'Michel LV 828',
          'Stamp Number LV 802',
          'Yvert et Tellier LV 802',
          'Stanley Gibbons LV 821',
        ],
        meta: {
          category: 'Plants (Flora)',
          designer: 'Lilija Dinere',
          faceValue: '35 Latvian santīms',
          printRun: '500,000',
        },
      },
      {
        year: '1968-03-12',
        country: 'Vatican City',
        src: '/stamps/monoline/vatican.svg',
        srcLg: '/stamps/monoline/lg/vatican.webp',
        srcOriginal: '/stamps/reference/vatican.webp',
        width: 180,
        catalogCodes: [
          'Michel VA 536',
          'Stamp Number VA C53',
          'Yvert et Tellier VA PA53',
          'Stanley Gibbons VA 511',
        ],
        meta: {
          category: 'Religion',
          designer: ['Egidio Vangelli', 'Tullio Mele'],
          faceValue: '1,000 Vatican lire',
          printRun: '13,250,000',
        },
      },
    ],
    colors: { bg: '#D3EEC9', fg: '#4D7C37', mutedBg: '#F2FAEF', mutedFg: '#99C883' },
  },
  dither: {
    colors: { bg: '#C3DEEE', fg: '#457AA1', mutedBg: '#EDF5FA', mutedFg: '#82ACCA' },
    stamps: [],
  },
};

export const collections = Object.fromEntries(
  Object.entries(baseCollections).map(([key, value]) => [
    key,
    {
      ...value,
      stamps: value.stamps.map((stamp: any, index) => ({
        ...stamp,
        id: stamp.id || `${key}-${index}`,
      })),
    },
  ]),
);

export type CollectionType = keyof typeof baseCollections;

export const collectionTypes = Object.keys(collections) as CollectionType[];

export const stamps = Object.values(collections).flatMap((collection) => collection.stamps);
