export const baseCollections = {
  typographic: {
    colors: { bg: '#F6DEB6', fg: '#C07E16', mutedBg: '#FCF3E5', mutedFg: '#ECB35A' },
    stamps: [
      {
        id: 't-01',
        year: '1971',
        category: 'Commemorative',
        country: 'Uruguay',
        src: '/stamps/typographic/stamp_01.png',
        srcLg: '/stamps/typographic/stamp_01.png',
        srcOriginal: '/stamps/typographic/image.png',
        catalogCodes: ['Michel UY 1123', 'Yvert UY 1050', 'SG UY 980'],
        designer: 'Estudio Nacional',
        faceValue: '0.50 UYU',
        meta: {
          faceValue: '0.50 UYU',
          perforation: '13½',
          printMethod: 'Offset',
          condition: 'Mint NH',
        },
      },
      {
        id: 't-02',
        year: '1972',
        category: 'Commemorative',
        country: 'Uruguay',
        src: '/stamps/typographic/stamp_02.png',
        srcLg: '/stamps/typographic/stamp_02.png',
        catalogCodes: ['Michel UY 1131', 'Yvert UY 1058', 'SG UY 988'],
        designer: 'Juan Manuel Blanes',
        meta: {
          faceValue: '1.00 UYU',
          perforation: '13',
          printMethod: 'Lithography',
          condition: 'Used F/VF',
        },
      },
      {
        id: 't-03',
        year: '1972',
        category: 'Commemorative',
        country: 'Uruguay',
        src: '/stamps/typographic/stamp_03.png',
        srcLg: '/stamps/typographic/stamp_03.png',
        catalogCodes: ['Michel UY 1132', 'Yvert UY 1059', 'SG UY 989', 'AFA UY 1132'],
        designer: 'Juan Manuel Blanes',
        meta: {
          faceValue: '1.20 UYU',
          perforation: '12½',
          printMethod: 'Recess',
          condition: 'Mint H',
        },
      },
      {
        id: 't-04',
        year: '1973',
        category: 'Semi-Postal',
        country: 'Uruguay',
        src: '/stamps/typographic/stamp_04.png',
        srcLg: '/stamps/typographic/stamp_04.png',
        catalogCodes: ['Michel UY B1140', 'Yvert UY 1068', 'SG UY 1002'],
        designer: 'María G. Prado',
        meta: {
          faceValue: '0.80+0.20 UYU',
          perforation: '14',
          printMethod: 'Offset',
          condition: 'Mint NH',
        },
      },
      {
        id: 't-05',
        year: '1974',
        category: 'Airmail',
        country: 'Uruguay',
        src: '/stamps/typographic/stamp_05.png',
        srcLg: '/stamps/typographic/stamp_05.png',
        catalogCodes: ['Michel UY C1151', 'Yvert UY PA1079', 'SG UY A1010'],
        designer: 'Carlos R. Soto',
        meta: {
          faceValue: '2.00 UYU',
          perforation: '13x13½',
          printMethod: 'Photogravure',
          condition: 'Mint NH',
        },
      },
      {
        id: 't-06',
        year: '1975',
        category: 'Definitive',
        country: 'Uruguay',
        src: '/stamps/typographic/stamp_06.png',
        srcLg: '/stamps/typographic/stamp_06.png',
        catalogCodes: ['Michel UY 1162', 'Yvert UY 1090', 'SG UY 1021'],
        designer: 'Estudio Nacional',
        meta: {
          faceValue: '0.10 UYU',
          perforation: '12',
          printMethod: 'Typography',
          condition: 'Used',
        },
      },
      {
        id: 't-07',
        year: '1976',
        category: 'Definitive',
        country: 'Uruguay',
        src: '/stamps/typographic/stamp_07.png',
        srcLg: '/stamps/typographic/stamp_07.png',
        catalogCodes: ['Michel UY 1170', 'Yvert UY 1098', 'SG UY 1029'],
        designer: 'L. Fernández',
        meta: {
          faceValue: '0.20 UYU',
          perforation: '12½',
          printMethod: 'Typography',
          condition: 'Mint H',
        },
      },
      {
        id: 't-08',
        year: '1977',
        category: 'Commemorative',
        country: 'Uruguay',
        src: '/stamps/typographic/stamp_08.png',
        srcLg: '/stamps/typographic/stamp_08.png',
        catalogCodes: ['Michel UY 1181', 'Yvert UY 1109', 'SG UY 1040'],
        designer: 'A. Rodríguez',
        meta: {
          faceValue: '3.00 UYU',
          perforation: '13',
          printMethod: 'Offset',
          condition: 'Mint NH',
        },
      },
    ],
  },
  textured: {
    stamps: [],
    colors: { bg: '#E5D2DD', fg: '#A45684', mutedBg: '#F8F3F6', mutedFg: '#CC9EB9' },
  },
  monoline: {
    stamps: [],
    colors: { bg: '#D3EEC9', fg: '#4D7C37', mutedBg: '#F2FAEF', mutedFg: '#99C883' },
  },

  other: {
    colors: { bg: '#C3DEEE', fg: '#457AA1', mutedBg: '#EDF5FA', mutedFg: '#82ACCA' },
    stamps: [
      {
        id: 'o-01',
        year: '1995',
        category: 'Commemorative',
        country: 'Algeria',
        src: '/stamps/algeria.png',
        srcLg: '/stamps/algeria.png',
        catalogCodes: ['Michel DZ 1234', 'Yvert DZ 1100', 'SG DZ 980'],
        designer: 'A. Benkhelifa',
        meta: {
          faceValue: '5.00 DZD',
          perforation: '13',
          printMethod: 'Offset',
          condition: 'Used',
        },
      },
      {
        id: 'o-02',
        year: '1990',
        category: 'Definitive',
        country: 'Germany',
        src: '/stamps/germany.png',
        srcLg: '/stamps/germany.png',
        catalogCodes: ['Michel DE 1450', 'Yvert DE 1250', 'SG DE 2100'],
        designer: 'Deutsche Bundespost',
        meta: {
          faceValue: '100 Pf',
          perforation: '14¼x14',
          printMethod: 'Recess',
          condition: 'Mint NH',
        },
      },
      {
        id: 'o-03',
        year: '1997',
        category: 'Children',
        country: 'Switzerland',
        src: '/stamps/pingu.png',
        srcLg: '/stamps/pingu.png',
        catalogCodes: ['Zumstein CH 2001', 'Yvert CH 1705', 'SG CH 1602'],
        designer: 'Trickfilmstudio Pingu',
        meta: {
          faceValue: '0.90 CHF',
          perforation: '13½',
          printMethod: 'Offset',
          condition: 'Mint NH',
        },
      },
      {
        id: 'o-04',
        year: '1962',
        category: 'Airmail',
        country: 'USA',
        src: '/stamps/seattle.png',
        srcLg: '/stamps/seattle.png',
        catalogCodes: ['Scott US C65', 'Yvert US PA65', 'SG US A100'],
        designer: 'USPS',
        meta: {
          faceValue: '15¢',
          perforation: '11',
          printMethod: 'Photogravure',
          condition: 'Used',
        },
      },
    ],
  },
};

export const collections = Object.fromEntries(
  Object.entries(baseCollections).map(([key, value]) => [
    key,
    {
      ...value,
      stamps: value.stamps.map((stamp, index) => ({
        ...stamp,
        id: stamp.id || `${key}-${index}`,
      })),
    },
  ]),
);

export const collectionTypes = Object.keys(collections) as CollectionType[];

export const stamps = Object.values(collections).flatMap((collection) => collection.stamps);

export type CollectionType = keyof typeof collections;
