export const collections = {
  typographic: {
    stamps: [
      {
        id: 1,
        year: '1972',
        category: 'Commemorative',
        country: 'Uruguay',
        src: '/stamps/typographic/8.svg',
        srcLg: '/stamps/typographic/8.svg',
        catalogCodes: [
          'Michel De-be 435',
          'Stamp number de 9nb92',
          'Yvert et Tellier DE-BE 400',
          'Stanley Gibbons DE-BE B424',
          'AFA number DE-BE 430',
          'Unificato DE-BE 400',
        ],
        designer: 'Juan Manuel Blanes',
        meta: {},
      },
      {
        id: 2,
        year: '1995',
        category: 'Commemorative',
        country: 'Croatia',
        src: '/stamps/typographic/8.svg',
        srcLg: '/stamps/typographic/8.svg',
        catalogCodes: [
          'Michel De-be 435',
          'Stamp number de 9nb92',
          'Yvert et Tellier DE-BE 400',
          'Stanley Gibbons DE-BE B424',
        ],
        designer: 'John Doe',
        meta: {},
      },
      {
        id: 3,
        year: '1995',
        category: 'Commemorative',
        country: 'Croatia',
        src: '/stamps/typographic/8.svg',
        srcLg: '/stamps/typographic/8.svg',
        catalogCodes: [
          'Michel De-be 435',
          'Stamp number de 9nb92',
          'Yvert et Tellier DE-BE 400',
          'Stanley Gibbons DE-BE B424',
        ],
        designer: 'John Doe',
        meta: {},
      },
      {
        id: 4,
        year: '1995',
        category: 'Commemorative',
        country: 'Croatia',
        src: '/stamps/typographic/8.svg',
        srcLg: '/stamps/typographic/8.svg',
        catalogCodes: [
          'Michel De-be 435',
          'Stamp number de 9nb92',
          'Yvert et Tellier DE-BE 400',
          'Stanley Gibbons DE-BE B424',
        ],
        designer: 'John Doe',
        meta: {},
      },
      {
        id: 5,
        year: '1995',
        category: 'Commemorative',
        country: 'Croatia',
        src: '/stamps/typographic/8.svg',
        srcLg: '/stamps/typographic/8.svg',
        catalogCodes: [
          'Michel De-be 435',
          'Stamp number de 9nb92',
          'Yvert et Tellier DE-BE 400',
          'Stanley Gibbons DE-BE B424',
        ],
        designer: 'John Doe',
        meta: {},
      },
      {
        id: 6,
        year: '1995',
        category: 'Commemorative',
        country: 'Croatia',
        src: '/stamps/typographic/8.svg',
        srcLg: '/stamps/typographic/8.svg',
        catalogCodes: [
          'Michel De-be 435',
          'Stamp number de 9nb92',
          'Yvert et Tellier DE-BE 400',
          'Stanley Gibbons DE-BE B424',
        ],
        designer: 'John Doe',
        meta: {},
      },
      // {
      //   id: 2,
      //   year: '1779',
      //   category: 'Historical',
      //   country: 'Gibraltar',
      //   src: '/stamps/typographic/2.svg',
      // },
      // {
      //   id: 3,
      //   year: '1985',
      //   category: 'Landscape',
      //   country: 'Argentina',
      //   src: '/stamps/typographic/3.svg',
      // },
      // {
      //   id: 4,
      //   year: '2001',
      //   category: 'Cultural',
      //   country: 'Spain',
      //   src: '/stamps/typographic/4.svg',
      // },
      // {
      //   id: 5,
      //   year: '1990',
      //   category: 'Flora',
      //   country: 'Brazil',
      //   src: '/stamps/typographic/5.svg',
      // },
      // {
      //   id: 6,
      //   year: '1968',
      //   category: 'Fauna',
      //   country: 'Peru',
      //   src: '/stamps/typographic/6.svg',
      // },
      // {
      //   id: 7,
      //   year: '1968',
      //   category: 'Fauna',
      //   country: 'Peru',
      //   src: '/stamps/typographic/7.svg',
      // },
    ],
  },
  monoline: {
    stamps: [],
    // stamps: [
    //   {
    //     id: 1,
    //     year: '1972',
    //     category: 'Commemorative',
    //     country: 'Uruguay',
    //     src: '/stamps/typographic/1.svg',
    //     catalogCodes: [
    //       'Michel De-be 435',
    //       'Stamp number de 9nb92',
    //       'Yvert et Tellier DE-BE 400',
    //       'Stanley Gibbons DE-BE B424',
    //       'AFA number DE-BE 430',
    //       'Unificato DE-BE 400',
    //     ],
    //     designer: 'Juan Manuel Blanes',
    //     meta: {},
    //   },
    //   {
    //     id: 2,
    //     year: '1779',
    //     category: 'Historical',
    //     country: 'Gibraltar',
    //     src: '/stamps/typographic/2.svg',
    //   },
    //   {
    //     id: 3,
    //     year: '1985',
    //     category: 'Landscape',
    //     country: 'Argentina',
    //     src: '/stamps/typographic/3.svg',
    //   },
    //   {
    //     id: 4,
    //     year: '2001',
    //     category: 'Cultural',
    //     country: 'Spain',
    //     src: '/stamps/typographic/4.svg',
    //   },
    //   {
    //     id: 5,
    //     year: '1990',
    //     category: 'Flora',
    //     country: 'Brazil',
    //     src: '/stamps/typographic/5.svg',
    //   },
    //   {
    //     id: 6,
    //     year: '1968',
    //     category: 'Fauna',
    //     country: 'Peru',
    //     src: '/stamps/typographic/6.svg',
    //   },
    //   {
    //     id: 7,
    //     year: '1968',
    //     category: 'Fauna',
    //     country: 'Peru',
    //     src: '/stamps/typographic/7.svg',
    //   },
    // ],
  },
  colored: {
    stamps: [],
  },
  dither: {
    stamps: [],
  },
};

collections.monoline = collections.typographic;
collections.colored = collections.typographic;
collections.dither = collections.typographic;

export const collectionTypes = Object.keys(collections) as CollectionType[];

export type CollectionType = keyof typeof collections;
